name: Docker Image CI

on:
  # https://docs.github.com/en/actions/using-workflows/events-that-trigger-workflows#schedule
  schedule:
    # The shortest interval you can run scheduled workflows is once every 5 minutes.
    # Note: The schedule event can be delayed during periods of high loads of GitHub Actions workflow runs.
    # High load times include the start of every hour.
    # To decrease the chance of delay, schedule your workflow to run at a different time of the hour.
    # Prime numbers are a good example for time of the hour: 3, 7, 11, 13, 17, 19, 23, 29, 31, 37, 41, 43, 47, 53
    # Example: every 5 minutes.
    # - cron: '*/5 * * * *'
    # Currently: every three days at 10:23am UTC.
    #- cron: "23 10 */3 * *"
    # - cron: "*/20 * * * *"
    # ONCE A YEAR
     - cron: "0 0 1 1 *"

#on:
#  push:
#    branches: [ "main" ]
#  pull_request:
#    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - name: Test initial directory contents
        run: |
          pwd
          ls -Rl
      - name: Build the Docker image
        run: docker build --tag ubuntu22.04-pandoc --file dockerfile .
      - name: Build the Docker container
        run: docker compose --file compose.yml up --detach
      - name: Run make inside the container
        run: docker exec -t pandoc-resume-generator make
      - name: Show me what happened
        run: |
          pwd
          ls -al output

      - uses: actions/upload-artifact@v4
        with:
          name: Completed Resumes
          path: output/

      - name: Clear README with intro text
        run: |
          cat README.md
          echo "# Welcome to my resume's CI/CD" > README.md
          echo "This repository keeps my resume up to date. Builds are done daily." >> README.md
          echo "  " >> README.md
          echo "You will find [the most recent builds](output/) of my resume here." >> README.md
          echo "* * *" >> README.md
          echo " " >> README.md
          echo "## The current date:  " >> README.md

      - name:
          Publish date to README.md
          # NOTE: UTC is adjusted to local MNT time. Please correct based on local standards.
        run: |
          cat README.md
          echo " $(date -d '-6 hour' +"%m/%d/%Y") " >> README.md
          echo "   " >> README.md
          echo "  " >> README.md
          echo "  " >> README.md
          echo " TIME PUBLISHED IS ALSO: " >> README.md
          echo "  " >> README.md
          echo " $(date -d '-6 hour' +"%I:%M.%S") " >> README.md
          echo "  " >> README.md
          echo "  " >> README.md
          cat README.md

      - name: Push to repository
        run: |
          git config --global user.name "ToddServo"
          git config --global user.email "16764933+ToddServo@users.noreply.github.com"
          now=$(date)
          git add -A
          git commit -m "Auto Push on $now"
          git push

      - name: Show me contents before quit
        run: |
          pwd
          ls -Rl
